DROP TABLE IF EXISTS user_data;

CREATE TABLE user_data (id Integer auto_increment PRIMARY KEY,first_name varchar(255) not NULL,email varchar(255) not NULL,company varchar(255), address varchar(255) not NULL,PRIMARY KEY (id));


INSERT INTO user_data (first_name,email,company,address) VALUES ('Alexa','Fusce.feugiat.Lorem@netus.ca','Sem Eget Massa Inc.','P.O. Box 486, 2867 Neque Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Silas','ut.pellentesque.eget@ridiculusmusProin.net','Elit Elit Ltd','141-1143 Ultrices. St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Kennan','mus.Donec.dignissim@Donecnon.com','Mauris Integer Institute','676 Diam. Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Demetrius','suscipit@eros.co.uk','Nulla Cras PC','P.O. Box 536, 2622 Auctor, St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Aphrodite','cubilia.Curae@ullamcorper.org','Hendrerit Corp.','1510 Consectetuer St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Whilemina','eget.dictum.placerat@consectetueradipiscing.edu','Lectus Nullam Suscipit Limited','Ap #809-7859 Libero Ave');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Jamalia','malesuada@Fusce.net','Id Libero LLP','269-7315 Phasellus Ave');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Emma','eleifend.nec.malesuada@auctorvelit.com','Aliquam Arcu Aliquam PC','Ap #787-721 Dictum Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Ian','aliquam.eu.accumsan@quamdignissim.org','Phasellus Associates','261-1578 Velit Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Ifeoma','Nullam@accumsanneque.net','Praesent Eu Nulla Foundation','Ap #596-7964 Placerat Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Jack','magnis@Maecenasmalesuada.com','Lacinia Vitae Inc.','P.O. Box 180, 1673 Quam. Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Rosalyn','feugiat.tellus.lorem@laoreetlectusquis.ca','Ligula Consectetuer Rhoncus LLC','596-1019 Justo Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Harriet','magna.et.ipsum@Aliquam.ca','Metus Facilisis Lorem Consulting','P.O. Box 608, 5501 Cum Avenue');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Kitra','sit.amet@sagittis.ca','Sed Turpis Nec Limited','1073 Neque Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Shaine','natoque.penatibus@nec.ca','Integer Tincidunt Associates','877-1557 Etiam Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Daniel','sagittis.placerat@euodiotristique.com','Sapien Associates','892-2930 Nec, Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Quincy','mi.ac@In.com','Elementum At LLC','905-9527 Lobortis Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Macon','tristique.senectus.et@erat.com','Non Ante Inc.','3781 Tempus Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Marvin','laoreet@NuncmaurisMorbi.com','Felis Ltd','Ap #307-771 Euismod Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Britanni','nascetur@ultrices.net','Molestie Consulting','714-7827 Ac Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Neil','urna.et@Etiamvestibulum.ca','Luctus Corp.','768-8365 Vel, Ave');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Keane','ut.pellentesque@montesnasceturridiculus.org','Semper Et Lacinia Consulting','8923 Eu Street');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Darius','dui@pellentesqueegetdictum.ca','Mollis PC','842-3269 Massa. Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Charlotte','quis@congueaaliquet.edu','Ut Mi Consulting','387-3967 Mattis St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Whoopi','vel.faucibus.id@elit.edu','Quisque Limited','P.O. Box 575, 3293 Ac Avenue');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Gage','auctor.odio@maurisanunc.co.uk','Sit Amet Associates','268-4678 Felis Ave');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Skyler','id.blandit.at@orciadipiscing.ca','Duis Risus Incorporated','4090 Ut, Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Kristen','Praesent.interdum.ligula@urnaUt.co.uk','A Associates','1217 Feugiat Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Sarah','at@habitantmorbi.net','Vitae Erat Vel PC','Ap #829-9686 Tellus Street');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Hadley','montes.nascetur@Nunclectus.co.uk','Cursus In Corp.','6932 Dolor. St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Graham','ultricies.adipiscing@sapienimperdietornare.net','Nisl Sem Consequat Corp.','Ap #463-2377 Quisque Ave');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Nicole','orci.Ut@arcuCurabiturut.com','Ante LLP','Ap #597-3890 Dapibus St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Bradley','vulputate@etmalesuada.edu','Non Sollicitudin A Corp.','Ap #655-5209 Facilisis, Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Carol','Nunc.mauris@malesuadafames.edu','Cras Institute','P.O. Box 587, 4152 Iaculis St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Deanna','Ut.nec.urna@orciluctuset.ca','Scelerisque Mollis Phasellus Incorporated','9672 Nibh Avenue');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Heather','tellus.Suspendisse@interdum.ca','At Lacus Quisque Company','1784 Lorem Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Rina','lacus@volutpatornarefacilisis.co.uk','Quisque Incorporated','P.O. Box 389, 7986 Volutpat. St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Pamela','est@dictumsapien.org','Rutrum Fusce Dolor LLP','Ap #456-5335 In Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Lacey','Donec.dignissim.magna@Nuncacsem.com','Vestibulum Mauris Magna Associates','P.O. Box 803, 6222 Lorem, Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Tatiana','molestie@Innecorci.edu','Eleifend Cras Associates','Ap #818-7143 Augue Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Rashad','risus@purusac.ca','Urna LLC','Ap #156-753 Mauris Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Porter','ultricies@natoque.net','Dis Parturient Montes Corporation','Ap #538-3465 Purus. Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Gil','et.magnis@mattisvelitjusto.com','Amet Lorem Semper Corporation','5342 Sodales. Street');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Montana','tellus.justo.sit@ornareplacerat.co.uk','Sit Amet Inc.','9212 Non, Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Dolan','taciti.sociosqu@metusurna.org','Enim Nisl Elementum Foundation','P.O. Box 774, 4148 Velit Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Charles','amet.ante.Vivamus@egestas.edu','Senectus Corporation','P.O. Box 448, 9952 Aliquet Street');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Chloe','semper.tellus.id@blandit.ca','Sagittis Nullam Vitae Associates','P.O. Box 152, 6780 Diam St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Kessie','porttitor@Quisqueporttitoreros.ca','Gravida Non Sollicitudin PC','P.O. Box 899, 4250 Faucibus Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Dane','mollis.nec@magnisdis.com','Quis LLP','466-4757 Ut Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Hadassah','et.libero.Proin@aliquet.ca','Fringilla Limited','8715 Integer Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Julian','elit@mauriserateget.net','Donec Tincidunt Donec LLP','9977 Nullam St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Christen','laoreet.posuere.enim@malesuadaInteger.edu','Et Nunc Quisque Institute','6431 A, Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Lysandra','fermentum.arcu.Vestibulum@tellus.net','Aliquam Industries','3183 Nisl. Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Alvin','in.sodales.elit@velmaurisInteger.net','Sapien LLC','8321 Orci. St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Curran','vulputate@quamquisdiam.com','Donec Fringilla Donec Foundation','Ap #476-3106 Nunc St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Clio','arcu@volutpatNullafacilisis.com','Eu Turpis Nulla Limited','4717 Diam Ave');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Brock','Praesent@auctor.com','Elementum Purus PC','P.O. Box 398, 4345 Gravida. Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Salvador','amet@Aliquamfringillacursus.co.uk','Amet Ornare Ltd','P.O. Box 631, 551 Cubilia St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Aphrodite','et@orci.org','Tincidunt Nunc Ac Associates','P.O. Box 396, 2361 A, St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Igor','turpis@purusgravida.net','Sed Industries','P.O. Box 420, 502 Auctor Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Lane','adipiscing.elit.Aliquam@Nullamvelitdui.org','Penatibus Et LLC','P.O. Box 343, 4903 Mollis. Ave');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Sacha','tellus@liberomaurisaliquam.edu','Tristique Pellentesque Institute','3344 Adipiscing. St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Kaitlin','Lorem.ipsum@ametconsectetueradipiscing.ca','Pellentesque Habitant Limited','695-4252 Enim Avenue');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Fulton','eu.nibh.vulputate@habitantmorbitristique.co.uk','Vel Consulting','5330 Dolor St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Veronica','at@Quisque.edu','Eget Dictum Placerat Associates','Ap #590-4324 Nunc Ave');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Shad','quis.urna.Nunc@dignissimtempor.co.uk','Sed Facilisis Vitae Consulting','Ap #356-8965 Cras Ave');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Courtney','vestibulum@fringillami.com','Aliquam Auctor Velit LLP','P.O. Box 663, 8625 Ultricies Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Nissim','Pellentesque.habitant.morbi@etmagnaPraesent.org','Vitae Posuere At Incorporated','455-1478 Nisi Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Oren','fermentum.arcu.Vestibulum@Sed.org','A Aliquet Vel LLP','952-7019 Tempor St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Cally','elit.a.feugiat@sitamet.net','Erat Eget Tincidunt Inc.','Ap #446-3158 Gravida. Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Jason','arcu.Vestibulum@enim.com','Scelerisque Mollis Inc.','Ap #120-9626 Ipsum Avenue');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Aileen','ad.litora@IncondimentumDonec.co.uk','Mauris Ipsum Institute','Ap #631-1890 Nonummy Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Herman','placerat.eget@id.ca','Proin Ultrices Duis Consulting','5844 Leo, Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Armando','felis.orci@nunc.com','Et Associates','P.O. Box 591, 8985 Sapien. Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Xyla','scelerisque@eu.co.uk','Nascetur Ridiculus Limited','P.O. Box 737, 3424 Et Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('George','sodales.Mauris@feugiatnec.net','Ante Ipsum LLP','8625 Et, Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Chiquita','quam@ettristiquepellentesque.ca','Mauris Vestibulum Neque Institute','P.O. Box 303, 8381 Aliquam St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Ali','Praesent@tempusloremfringilla.co.uk','Felis PC','8053 Nullam Street');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Mariam','primis.in.faucibus@lacus.com','Dolor Nulla Semper Consulting','Ap #993-4951 Tempor, Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Igor','non.justo@sapienCras.edu','Justo Sit Amet Inc.','P.O. Box 412, 4679 Tellus Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Merritt','eget.metus.In@accumsannequeet.co.uk','Ultricies Industries','P.O. Box 463, 1993 At, Avenue');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Nadine','erat.Sed@tellus.org','Amet Diam Eu Corp.','P.O. Box 703, 8777 Libero. Street');
INSERT INTO user_data (first_name,email,company,address) VALUES ('James','vitae.nibh.Donec@neque.co.uk','Felis Adipiscing Institute','Ap #342-2538 Sed Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('MacKensie','feugiat.Sed.nec@lectusrutrumurna.edu','Tellus Incorporated','P.O. Box 966, 7562 Aliquet, Avenue');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Solomon','ornare@penatibuset.edu','Ipsum Leo Company','Ap #821-6113 Elit St.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Gregory','neque.et@Maecenasmifelis.com','Ultricies Adipiscing Associates','158-6611 Ornare, Avenue');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Mira','ut@tincidunt.org','Lectus Corp.','764-7173 Ut, Street');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Rhea','Sed@massa.edu','Ligula Aliquam Erat Industries','P.O. Box 119, 7463 Ridiculus Road');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Danielle','enim.sit@aliquameuaccumsan.edu','Eros Non Enim Foundation','P.O. Box 369, 7080 Fringilla Street');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Karen','tempus.non@pede.co.uk','Mattis Semper Dui Institute','299-9370 Urna. Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Nathan','ligula.consectetuer.rhoncus@mi.co.uk','Non Associates','656-8213 Amet Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Eaton','nisi.magna.sed@vitae.co.uk','Montes Nascetur Associates','275 Tellus Avenue');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Maya','montes.nascetur.ridiculus@malesuadaInteger.org','Imperdiet Ullamcorper Inc.','P.O. Box 825, 1545 Sem Street');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Jane','magna.Duis@acliberonec.com','Malesuada Malesuada Integer LLC','P.O. Box 131, 8895 Pellentesque Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Mia','Cras.vulputate.velit@quispedePraesent.net','Risus Industries','7305 Montes, Ave');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Abbot','consectetuer.rhoncus@ametluctus.ca','Dolor Nulla Semper Company','9385 Nec, Rd.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Violet','mauris@Praesentinterdumligula.org','Sapien Incorporated','350-9271 At, Av.');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Porter','Integer@dictumeueleifend.net','Quam Quis LLP','Ap #977-3967 Ut, Avenue');
INSERT INTO user_data (first_name,email,company,address) VALUES ('Shaeleigh','tristique.senectus.et@enimSuspendisse.com','Pede Suspendisse Industries','221-257 Bibendum Rd.');
